# Generated by Django 5.2.9 on 2026-04-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
    ]
